// src/components/Controls.tsx
import { useState, useRef, useEffect } from 'react';
import { BPM_MIN, BPM_MAX, REPS_MIN, REPS_MAX, GOOD_SCORE_THRESHOLD, OK_SCORE_THRESHOLD } from '../config/constants';
import type { SessionResult } from '../types';
import './Controls.css';

interface ControlsProps {
  isPlaying: boolean;
  onTogglePlay: () => void;
  onStop: () => void;
  bpm: number;
  trainingMode: boolean;
  onTrainingToggle: () => void;
  accuracyStats?: { score: number; perfect: number; good: number; off: number; miss: number; total: number } | null;
  missedHits: number;
  bpmOverride: number | null;
  onBpmChange: (bpm: number) => void;
  stopAfterReps: number;
  onStopAfterRepsChange: (reps: number) => void;
  currentLoop: number;
  sessionResult: SessionResult | null;
  onDismissResult: () => void;
  showVisualizer: boolean;
  onToggleVisualizer: () => void;
  metronomeOn: boolean;
  onToggleMetronome: () => void;
  drumPlaybackOn: boolean;
  onToggleDrumPlayback: () => void;
  countdownOn: boolean;
  onCountdownToggle: () => void;
  grooveOn: boolean;
  onGrooveToggle: () => void;
  edgeMode: boolean;
  onEdgeModeToggle: () => void;
  trackMode: boolean;
  trackName?: string;
  trackPart: number;
  trackTotalParts: number;
}

export default function Controls({
  isPlaying, onTogglePlay, onStop, bpm,
  trainingMode, onTrainingToggle,
  bpmOverride: _bpmOverride, onBpmChange,
  stopAfterReps, onStopAfterRepsChange, currentLoop,
  sessionResult, onDismissResult,
  showVisualizer, onToggleVisualizer,
  metronomeOn, onToggleMetronome,
  drumPlaybackOn, onToggleDrumPlayback,
  countdownOn, onCountdownToggle,
  grooveOn, onGrooveToggle,
  edgeMode, onEdgeModeToggle,
  trackMode, trackName, trackPart, trackTotalParts,
}: ControlsProps) {
  const [showBpm, setShowBpm] = useState(false);
  const [showReps, setShowReps] = useState(false);
  const bpmRef = useRef<HTMLDivElement>(null);
  const repsRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!showBpm) return;
    const handler = (e: MouseEvent) => {
      if (bpmRef.current && !bpmRef.current.contains(e.target as Node)) {
        setShowBpm(false);
      }
    };
    document.addEventListener('mousedown', handler);
    document.addEventListener('touchstart', handler as EventListener);
    return () => {
      document.removeEventListener('mousedown', handler);
      document.removeEventListener('touchstart', handler as EventListener);
    };
  }, [showBpm]);

  useEffect(() => {
    if (!showReps) return;
    const handler = (e: MouseEvent) => {
      if (repsRef.current && !repsRef.current.contains(e.target as Node)) {
        setShowReps(false);
      }
    };
    document.addEventListener('mousedown', handler);
    document.addEventListener('touchstart', handler as EventListener);
    return () => {
      document.removeEventListener('mousedown', handler);
      document.removeEventListener('touchstart', handler as EventListener);
    };
  }, [showReps]);
  const hasSessionResult = sessionResult && sessionResult.stats;

  useEffect(() => {
    if (!hasSessionResult) return;
    const handler = (e: KeyboardEvent) => {
      if (e.code === 'Space') {
        e.preventDefault();
        onDismissResult();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [hasSessionResult, onDismissResult]);

  return (
    <div className="controls">
      <div className="controls-row">
        <div className="controls-group">
          <button className={`btn btn-play ${isPlaying ? 'playing' : ''}`} onClick={onTogglePlay}>
            {isPlaying ? '⏸' : '▶'}
          </button>
          <button className="btn btn-stop" onClick={onStop}>⏹</button>
        </div>

        {trackMode && (
          <div className="controls-group track-info-group">
            <span className="track-info-label">{trackName}</span>
            <span className="track-info-progress">Part {trackPart + 1}/{trackTotalParts}</span>
          </div>
        )}

        <div className="controls-group bpm-wrap" ref={bpmRef}>
          <button
            className={`btn btn-bpm ${showBpm ? 'active' : ''}`}
            onClick={() => setShowBpm(v => !v)}
            title="BPM"
          >
            <span className="bpm-value">{bpm}</span>
          </button>
          {showBpm && (
            <div className="bpm-popup">
              <input
                type="range"
                className="bpm-slider"
                min={BPM_MIN}
                max={BPM_MAX}
                step="1"
                value={bpm}
                onChange={e => onBpmChange(Number(e.target.value))}
              />
              <input
                type="number"
                className="bpm-input"
                min={BPM_MIN}
                max={BPM_MAX}
                value={bpm}
                onChange={e => {
                  const v = Number(e.target.value);
                  if (v >= BPM_MIN && v <= BPM_MAX) onBpmChange(v);
                }}
              />
            </div>
          )}
        </div>

        {trainingMode && (
          <div className="controls-group reps-wrap" ref={repsRef}>
            <button
              className={`btn btn-reps ${showReps ? 'active' : ''}`}
              onClick={() => setShowReps(v => !v)}
              title="Reps"
            >
              <span className="reps-value">{stopAfterReps || REPS_MIN}</span>
            </button>
            {showReps && (
              <div className="reps-popup">
                <input
                  type="range"
                  className="reps-slider"
                  min={REPS_MIN}
                  max={REPS_MAX}
                  step="1"
                  value={stopAfterReps || REPS_MIN}
                  onChange={e => onStopAfterRepsChange(Number(e.target.value))}
                />
                <input
                  type="number"
                  className="reps-input"
                  min={REPS_MIN}
                  max={REPS_MAX}
                  value={stopAfterReps}
                  onChange={e => {
                    const v = Number(e.target.value);
                    if (v >= REPS_MIN && v <= REPS_MAX) onStopAfterRepsChange(v);
                  }}
                />
                {isPlaying && stopAfterReps > 0 && (
                  <span className="reps-counter">{currentLoop}/{stopAfterReps}</span>
                )}
              </div>
            )}
          </div>
        )}

        <div className="controls-group">
          <button
            className={`btn btn-countdown ${countdownOn ? 'active' : 'off'}`}
            onClick={onCountdownToggle}
          >
            🚦
          </button>
        </div>

        <div className="controls-group">
          <button
            className={`btn btn-groove ${grooveOn ? 'active' : 'off'}`}
            onClick={onGrooveToggle}
          >
            🔀
          </button>
        </div>

        <div className="controls-group">
          <button
            className={`btn btn-edge ${edgeMode ? 'active' : 'off'}`}
            onClick={onEdgeModeToggle}
            title={`Edge mode: ${edgeMode ? 'ON' : 'OFF'} — replaces standard hi-hats with edge/top articulation`}
          >
            🎛
          </button>
        </div>

        <div className="controls-group">
          <button
            className={`btn btn-metronome ${metronomeOn ? 'active' : 'off'}`}
            onClick={onToggleMetronome}
          >
            🔊
          </button>
        </div>

        <div className="controls-group">
          <button
            className={`btn btn-drum-playback ${drumPlaybackOn ? 'active' : 'off'}`}
            onClick={onToggleDrumPlayback}
          >
            🥁
          </button>
        </div>

        <div className="controls-group">
          <button
            className={`btn btn-training ${trainingMode ? 'active' : 'off'}`}
            onClick={onTrainingToggle}
          >
            🎯
          </button>
        </div>

        <div className="controls-group">
          <button
            className={`btn btn-visualizer ${showVisualizer ? 'active' : 'off'}`}
            onClick={onToggleVisualizer}
          >
            📊
          </button>
        </div>


      </div>

      {hasSessionResult && (
        <div className="session-overlay" onClick={onDismissResult}>
          <div className="session-modal" onClick={e => e.stopPropagation()}>
            <h2 className="session-modal-title">Session Complete</h2>
            <div className="session-modal-score">
              <span className={`score-value ${sessionResult.stats.score >= GOOD_SCORE_THRESHOLD ? 'good' : sessionResult.stats.score >= OK_SCORE_THRESHOLD ? 'ok' : 'bad'}`}>
                {sessionResult.stats.score}%
              </span>
              <span className="score-label">Accuracy</span>
            </div>
            <div className="session-modal-stats">
              <div className="stat">
                <span className="stat-label">Perfect</span>
                <span className="stat-value perfect">{sessionResult.stats.perfect}</span>
              </div>
              <div className="stat">
                <span className="stat-label">Good</span>
                <span className="stat-value good">{sessionResult.stats.good}</span>
              </div>
              <div className="stat">
                <span className="stat-label">Off</span>
                <span className="stat-value off">{sessionResult.stats.off}</span>
              </div>
              <div className="stat">
                <span className="stat-label">Extra</span>
                <span className="stat-value miss">{sessionResult.stats.miss}</span>
              </div>
              <div className="stat">
                <span className="stat-label">Missed</span>
                <span className="stat-value miss">{sessionResult.missedHits ?? 0}</span>
              </div>
              <div className="stat">
                <span className="stat-label">Total</span>
                <span className="stat-value total">{sessionResult.stats.total}</span>
              </div>
            </div>
            <button className="btn btn-dismiss" onClick={onDismissResult}>Dismiss</button>
          </div>
        </div>
      )}

    </div>
  );
}

// src/components/Controls.svelte
<script lang="ts">
  import { GOOD_SCORE_THRESHOLD, OK_SCORE_THRESHOLD } from '../config/constants';
  import type { SessionResult } from '../types';
  import BpmPopup from './BpmPopup.svelte';
  import RepsPopup from './RepsPopup.svelte';
  import './Controls.css';

  interface Props {
    isPlaying: boolean;
    onTogglePlay: () => void;
    onStop: () => void;
    bpm: number;
    trainingMode: boolean;
    onTrainingToggle: () => void;
    accuracyStats?: { score: number; perfect: number; good: number; off: number; miss: number; total: number } | null;
    missedHits: number;
    bpmOverride: number | null;
    onBpmChange: (bpm: number) => void;
    stopAfterReps: number;
    onStopAfterRepsChange: (reps: number) => void;
    currentLoop: number;
    sessionResult: SessionResult | null;
    onDismissResult: () => void;
    showVisualizer: boolean;
    onToggleVisualizer: () => void;
    metronomeOn: boolean;
    onToggleMetronome: () => void;
    drumPlaybackOn: boolean;
    onToggleDrumPlayback: () => void;
    countdownOn: boolean;
    onCountdownToggle: () => void;
    grooveOn: boolean;
    onGrooveToggle: () => void;
    edgeMode: boolean;
    onEdgeModeToggle: () => void;
    trackMode: boolean;
    trackName?: string;
    trackPart: number;
    trackTotalParts: number;
  }

  let {
    isPlaying,
    onTogglePlay,
    onStop,
    bpm,
    trainingMode,
    onTrainingToggle,
    bpmOverride: _bpmOverride,
    onBpmChange,
    stopAfterReps,
    onStopAfterRepsChange,
    currentLoop,
    sessionResult,
    onDismissResult,
    showVisualizer,
    onToggleVisualizer,
    metronomeOn,
    onToggleMetronome,
    drumPlaybackOn,
    onToggleDrumPlayback,
    countdownOn,
    onCountdownToggle,
    grooveOn,
    onGrooveToggle,
    edgeMode,
    onEdgeModeToggle,
    trackMode,
    trackName,
    trackPart,
    trackTotalParts,
  }: Props = $props();

  let hasSessionResult = $derived(sessionResult && sessionResult.stats);

  $effect(() => {
    if (!hasSessionResult) return;
    const handler = (e: KeyboardEvent) => {
      if (e.code === 'Space') {
        e.preventDefault();
        onDismissResult();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  });
</script>

<div class="controls">
  <div class="controls-row">
    <div class="controls-group">
      <button class="btn btn-play {isPlaying ? 'playing' : ''}" onclick={onTogglePlay}>
        {isPlaying ? '⏸' : '▶'}
      </button>
      <button class="btn btn-stop" onclick={onStop}>⏹</button>
    </div>

    {#if trackMode}
      <div class="controls-group track-info-group">
        <span class="track-info-label">{trackName}</span>
        <span class="track-info-progress">Part {trackPart + 1}/{trackTotalParts}</span>
      </div>
    {/if}

    <div class="controls-group">
      <BpmPopup
        {bpm}
        {onBpmChange}
        buttonClass="btn btn-bpm"
        popupClass="bpm-popup"
        sliderClass="bpm-slider"
        inputClass="bpm-input"
        wrapperClass="bpm-wrap"
      />
    </div>

    {#if trainingMode}
      <div class="controls-group">
        <RepsPopup
          {stopAfterReps}
          {onStopAfterRepsChange}
          {isPlaying}
          {currentLoop}
          buttonClass="btn btn-reps"
          popupClass="reps-popup"
          sliderClass="reps-slider"
          inputClass="reps-input"
          wrapperClass="reps-wrap"
          counterClass="reps-counter"
        />
      </div>
    {/if}

    <div class="controls-group">
      <button
        class="btn btn-countdown {countdownOn ? 'active' : 'off'}"
        onclick={onCountdownToggle}
      >
        🚦
      </button>
    </div>

    <div class="controls-group">
      <button
        class="btn btn-groove {grooveOn ? 'active' : 'off'}"
        onclick={onGrooveToggle}
      >
        🔀
      </button>
    </div>

    <div class="controls-group">
      <button
        class="btn btn-edge {edgeMode ? 'active' : 'off'}"
        onclick={onEdgeModeToggle}
        title="Edge mode: {edgeMode ? 'ON' : 'OFF'} — replaces standard hi-hats with edge/top articulation"
      >
        🎛
      </button>
    </div>

    <div class="controls-group">
      <button
        class="btn btn-metronome {metronomeOn ? 'active' : 'off'}"
        onclick={onToggleMetronome}
      >
        🔊
      </button>
    </div>

    <div class="controls-group">
      <button
        class="btn btn-drum-playback {drumPlaybackOn ? 'active' : 'off'}"
        onclick={onToggleDrumPlayback}
      >
        🥁
      </button>
    </div>

    <div class="controls-group">
      <button
        class="btn btn-training {trainingMode ? 'active' : 'off'}"
        onclick={onTrainingToggle}
      >
        🎯
      </button>
    </div>

    <div class="controls-group">
      <button
        class="btn btn-visualizer {showVisualizer ? 'active' : 'off'}"
        onclick={onToggleVisualizer}
      >
        📊
      </button>
    </div>
  </div>

  {#if hasSessionResult}
    <div class="session-overlay" onclick={onDismissResult}>
      <div class="session-modal" onclick={(e) => e.stopPropagation()}>
        <h2 class="session-modal-title">Session Complete</h2>
        <div class="session-modal-score">
          <span class="score-value {sessionResult.stats.score >= GOOD_SCORE_THRESHOLD ? 'good' : sessionResult.stats.score >= OK_SCORE_THRESHOLD ? 'ok' : 'bad'}">
            {sessionResult.stats.score}%
          </span>
          <span class="score-label">Accuracy</span>
        </div>
        <div class="session-modal-stats">
          <div class="stat">
            <span class="stat-label">Perfect</span>
            <span class="stat-value perfect">{sessionResult.stats.perfect}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Good</span>
            <span class="stat-value good">{sessionResult.stats.good}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Off</span>
            <span class="stat-value off">{sessionResult.stats.off}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Extra</span>
            <span class="stat-value miss">{sessionResult.stats.miss}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Missed</span>
            <span class="stat-value miss">{sessionResult.missedHits ?? 0}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Total</span>
            <span class="stat-value total">{sessionResult.stats.total}</span>
          </div>
        </div>
        <button class="btn btn-dismiss" onclick={onDismissResult}>Dismiss</button>
      </div>
    </div>
  {/if}
</div>
