// src/components/FullscreenControls.tsx
import { useState, useRef, useEffect } from 'react';
import { BPM_MIN, BPM_MAX, REPS_MIN, REPS_MAX } from '../config/constants';
import './FullscreenControls.css';

interface FullscreenControlsProps {
  isPlaying: boolean;
  onTogglePlay: () => void;
  onStop: () => void;
  bpm: number;
  onBpmChange: (bpm: number) => void;
  drumPlaybackOn: boolean;
  onToggleDrumPlayback: () => void;
  trainingMode: boolean;
  onTrainingToggle: () => void;
  stopAfterReps: number;
  onStopAfterRepsChange: (reps: number) => void;
  currentLoop: number;
  grooveOn: boolean;
  onGrooveToggle: () => void;
  countdownOn: boolean;
  onCountdownToggle: () => void;
}

export default function FullscreenControls({
  isPlaying, onTogglePlay, onStop, bpm, onBpmChange,
  drumPlaybackOn, onToggleDrumPlayback,
  trainingMode, onTrainingToggle,
  stopAfterReps, onStopAfterRepsChange, currentLoop,
  grooveOn, onGrooveToggle,
  countdownOn, onCountdownToggle,
}: FullscreenControlsProps) {
  const [showBpm, setShowBpm] = useState(false);
  const [showReps, setShowReps] = useState(false);
  const bpmRef = useRef<HTMLDivElement>(null);
  const repsRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!showBpm) return;
    const handler = (e: MouseEvent) => {
      if (bpmRef.current && !bpmRef.current.contains(e.target as Node)) {
        setShowBpm(false);
      }
    };
    document.addEventListener('mousedown', handler);
    document.addEventListener('touchstart', handler as EventListener);
    return () => {
      document.removeEventListener('mousedown', handler);
      document.removeEventListener('touchstart', handler as EventListener);
    };
  }, [showBpm]);

  useEffect(() => {
    if (!showReps) return;
    const handler = (e: MouseEvent) => {
      if (repsRef.current && !repsRef.current.contains(e.target as Node)) {
        setShowReps(false);
      }
    };
    document.addEventListener('mousedown', handler);
    document.addEventListener('touchstart', handler as EventListener);
    return () => {
      document.removeEventListener('mousedown', handler);
      document.removeEventListener('touchstart', handler as EventListener);
    };
  }, [showReps]);

  const showPlaying = isPlaying;

  return (
    <div className="fullscreen-controls">
      <div className="fs-controls-row">
        <button
          className={`fs-btn fs-btn-play ${showPlaying ? 'playing' : ''}`}
          onClick={onTogglePlay}
          title={showPlaying ? 'Pause' : 'Play'}
        >
          {showPlaying ? '⏸' : '▶'}
        </button>
        <button className="fs-btn fs-btn-stop" onClick={onStop} title="Stop">
          ⏹
        </button>

        <button
          className={`fs-btn ${drumPlaybackOn ? 'active' : 'off'}`}
          onClick={onToggleDrumPlayback}
          title={drumPlaybackOn ? 'Pattern On' : 'Pattern Off'}
        >
          🥁
        </button>

        <button
          className={`fs-btn ${trainingMode ? 'active' : 'off'}`}
          onClick={onTrainingToggle}
          title={trainingMode ? 'Training On' : 'Training Off'}
        >
          🎯
        </button>

        <button
          className={`fs-btn ${grooveOn ? 'active' : 'off'}`}
          onClick={onGrooveToggle}
          title={grooveOn ? 'Groove On' : 'Groove Off'}
        >
          🔀
        </button>

        <button
          className={`fs-btn ${countdownOn ? 'active' : 'off'}`}
          onClick={onCountdownToggle}
          title={countdownOn ? 'Countdown On' : 'Countdown Off'}
        >
          🚦
        </button>

        <div className="fs-separator" />

        {trainingMode && (
          <div className="fs-reps-wrap" ref={repsRef}>
            <button
              className={`fs-btn fs-btn-reps ${showReps ? 'active' : ''}`}
              onClick={() => setShowReps(v => !v)}
              title="Reps"
            >
              <span className="fs-reps-value">{stopAfterReps || REPS_MIN}</span>
            </button>
            {showReps && (
              <div className="fs-reps-popup">
                <input
                  type="range"
                  className="fs-reps-slider"
                  min={REPS_MIN}
                  max={REPS_MAX}
                  step="1"
                  value={stopAfterReps || REPS_MIN}
                  onChange={e => onStopAfterRepsChange(Number(e.target.value))}
                />
                <input
                  type="number"
                  className="fs-reps-input"
                  min={REPS_MIN}
                  max={REPS_MAX}
                  value={stopAfterReps}
                  onChange={e => {
                    const v = Number(e.target.value);
                    if (v >= REPS_MIN && v <= REPS_MAX) onStopAfterRepsChange(v);
                  }}
                />
                {showPlaying && stopAfterReps > 0 && (
                  <span className="fs-reps-counter">{currentLoop}/{stopAfterReps}</span>
                )}
              </div>
            )}
          </div>
        )}

        <div className="fs-bpm-wrap" ref={bpmRef}>
          <button
            className={`fs-btn fs-btn-bpm ${showBpm ? 'active' : ''}`}
            onClick={() => setShowBpm(v => !v)}
            title="BPM"
          >
            <span className="fs-bpm-value">{bpm}</span>
          </button>
          {showBpm && (
            <div className="fs-bpm-popup">
              <input
                type="range"
                className="fs-bpm-slider"
                min={BPM_MIN}
                max={BPM_MAX}
                step="1"
                value={bpm}
                onChange={e => onBpmChange(Number(e.target.value))}
              />
              <input
                type="number"
                className="fs-bpm-input"
                min={BPM_MIN}
                max={BPM_MAX}
                value={bpm}
                onChange={e => {
                  const v = Number(e.target.value);
                  if (v >= BPM_MIN && v <= BPM_MAX) onBpmChange(v);
                }}
              />
            </div>
          )}
        </div>
      </div>

    </div>
  );
}

// src/components/FullscreenControls.svelte
<script lang="ts">
  import BpmPopup from './BpmPopup.svelte';
  import RepsPopup from './RepsPopup.svelte';
  import './FullscreenControls.css';

  interface Props {
    isPlaying: boolean;
    onTogglePlay: () => void;
    onStop: () => void;
    bpm: number;
    onBpmChange: (bpm: number) => void;
    drumPlaybackOn: boolean;
    onToggleDrumPlayback: () => void;
    trainingMode: boolean;
    onTrainingToggle: () => void;
    stopAfterReps: number;
    onStopAfterRepsChange: (reps: number) => void;
    currentLoop: number;
    grooveOn: boolean;
    onGrooveToggle: () => void;
    countdownOn: boolean;
    onCountdownToggle: () => void;
  }

  let {
    isPlaying,
    onTogglePlay,
    onStop,
    bpm,
    onBpmChange,
    drumPlaybackOn,
    onToggleDrumPlayback,
    trainingMode,
    onTrainingToggle,
    stopAfterReps,
    onStopAfterRepsChange,
    currentLoop,
    grooveOn,
    onGrooveToggle,
    countdownOn,
    onCountdownToggle,
  }: Props = $props();

  let showPlaying = $derived(isPlaying);
</script>

<div class="fullscreen-controls">
  <div class="fs-controls-row">
    <button
      class="fs-btn fs-btn-play {showPlaying ? 'playing' : ''}"
      onclick={onTogglePlay}
      title={showPlaying ? 'Pause' : 'Play'}
    >
      {showPlaying ? '⏸' : '▶'}
    </button>
    <button class="fs-btn fs-btn-stop" onclick={onStop} title="Stop">
      ⏹
    </button>

    <button
      class="fs-btn {drumPlaybackOn ? 'active' : 'off'}"
      onclick={onToggleDrumPlayback}
      title={drumPlaybackOn ? 'Pattern On' : 'Pattern Off'}
    >
      🥁
    </button>

    <button
      class="fs-btn {trainingMode ? 'active' : 'off'}"
      onclick={onTrainingToggle}
      title={trainingMode ? 'Training On' : 'Training Off'}
    >
      🎯
    </button>

    <button
      class="fs-btn {grooveOn ? 'active' : 'off'}"
      onclick={onGrooveToggle}
      title={grooveOn ? 'Groove On' : 'Groove Off'}
    >
      🔀
    </button>

    <button
      class="fs-btn {countdownOn ? 'active' : 'off'}"
      onclick={onCountdownToggle}
      title={countdownOn ? 'Countdown On' : 'Countdown Off'}
    >
      🚦
    </button>

    <div class="fs-separator"></div>

    {#if trainingMode}
      <RepsPopup
        {stopAfterReps}
        {onStopAfterRepsChange}
        isPlaying={showPlaying}
        {currentLoop}
        buttonClass="fs-btn fs-btn-reps"
        popupClass="fs-reps-popup"
        sliderClass="fs-reps-slider"
        inputClass="fs-reps-input"
        wrapperClass="fs-reps-wrap"
        counterClass="fs-reps-counter"
      />
    {/if}

    <BpmPopup
      {bpm}
      {onBpmChange}
      buttonClass="fs-btn fs-btn-bpm"
      popupClass="fs-bpm-popup"
      sliderClass="fs-bpm-slider"
      inputClass="fs-bpm-input"
      wrapperClass="fs-bpm-wrap"
    />
  </div>
</div>
