// src/components/TrackMenu.jsx
import { useMemo } from 'react';
import { trackList } from '../data/trackList';
import './TrackMenu.css';

export default function TrackMenu({ selectedTrackId, currentTrackName, onSelectTrack, isPlayingTrack, trackPart, trackTotalParts, embedded, activeStyles }) {
  const grouped = useMemo(() => {
    const filtered = activeStyles.length === 0
      ? trackList
      : trackList.filter(t => activeStyles.includes(t.style));
    const map = {};
    for (const t of filtered) {
      const s = t.style || 'Other';
      if (!map[s]) map[s] = [];
      map[s].push(t);
    }
    return map;
  }, [activeStyles]);

  const content = (
    <div className="track-list">
      {Object.entries(grouped).map(([style, tracks]) => (
        <div key={style}>
          <div className="style-group-header">{style}</div>
          {tracks.map(track => {
            const isActive = track.id === selectedTrackId;
            return (
              <button
                key={track.id}
                className={`track-item ${isActive ? 'active' : ''}`}
                onClick={() => onSelectTrack(track.id)}
              >
                <div className="track-info">
                  <span className="track-name">{track.name}</span>
                  <span className="track-desc">{track.description}</span>
                  {isActive && isPlayingTrack && (
                    <span className="track-progress">
                      Part {trackPart + 1} / {trackTotalParts}
                    </span>
                  )}
                  {isActive && currentTrackName && (
                    <span className="track-current-pattern">{currentTrackName}</span>
                  )}
                </div>
                <span className="track-bpm">{track.bpm} BPM</span>
              </button>
            );
          })}
        </div>
      ))}
    </div>
  );

  if (embedded) return content;

  return (
    <div className="track-menu">
      <div className="menu-section">
        <h2 className="menu-section-title">Tracks</h2>
        {content}
      </div>
    </div>
  );
}

// src/components/TrackMenu.svelte
<script lang="ts">
  import { trackList } from '../data/trackList';
  import './TrackMenu.css';

  interface Props {
    selectedTrackId: string | null;
    currentTrackName?: string;
    onSelectTrack: (id: string) => void;
    isPlayingTrack: boolean;
    trackPart: number;
    trackTotalParts: number;
    embedded?: boolean;
    activeStyles?: string[];
  }

  let {
    selectedTrackId,
    currentTrackName = '',
    onSelectTrack,
    isPlayingTrack,
    trackPart,
    trackTotalParts,
    embedded = false,
    activeStyles = [],
  }: Props = $props();

  let grouped = $derived.by(() => {
    const filtered = activeStyles.length === 0
      ? trackList
      : trackList.filter(t => activeStyles.includes(t.style));
    const map: Record<string, typeof trackList> = {};
    for (const t of filtered) {
      const s = t.style || 'Other';
      if (!map[s]) map[s] = [];
      map[s].push(t);
    }
    return map;
  });
</script>

{#if embedded}
  <div class="track-list">
    {#each Object.entries(grouped) as [style, tracks]}
      <div>
        <div class="style-group-header">{style}</div>
        {#each tracks as track (track.id)}
          {@const isActive = track.id === selectedTrackId}
          <button
            class="track-item {isActive ? 'active' : ''}"
            onclick={() => onSelectTrack(track.id)}
          >
            <div class="track-info">
              <span class="track-name">{track.name}</span>
              <span class="track-desc">{track.description}</span>
              {#if isActive && isPlayingTrack}
                <span class="track-progress">
                  Part {trackPart + 1} / {trackTotalParts}
                </span>
              {/if}
              {#if isActive && currentTrackName}
                <span class="track-current-pattern">{currentTrackName}</span>
              {/if}
            </div>
            <span class="track-bpm">{track.bpm} BPM</span>
          </button>
        {/each}
      </div>
    {/each}
  </div>
{:else}
  <div class="track-menu">
    <div class="menu-section">
      <h2 class="menu-section-title">Tracks</h2>
      <div class="track-list">
        {#each Object.entries(grouped) as [style, tracks]}
          <div>
            <div class="style-group-header">{style}</div>
            {#each tracks as track (track.id)}
              {@const isActive = track.id === selectedTrackId}
              <button
                class="track-item {isActive ? 'active' : ''}"
                onclick={() => onSelectTrack(track.id)}
              >
                <div class="track-info">
                  <span class="track-name">{track.name}</span>
                  <span class="track-desc">{track.description}</span>
                  {#if isActive && isPlayingTrack}
                    <span class="track-progress">
                      Part {trackPart + 1} / {trackTotalParts}
                    </span>
                  {/if}
                  {#if isActive && currentTrackName}
                    <span class="track-current-pattern">{currentTrackName}</span>
                  {/if}
                </div>
                <span class="track-bpm">{track.bpm} BPM</span>
              </button>
            {/each}
          </div>
        {/each}
      </div>
    </div>
  </div>
{/if}
