// src/App.svelte
<script lang="ts">
  import './App.css';
  import Timeline from './components/Timeline.svelte';
  import PatternTrackTabs from './components/PatternTrackTabs.svelte';
  import Controls from './components/Controls.svelte';
  import DrumVisualizer from './components/DrumVisualizer.svelte';
  import HelpModal from './components/HelpModal.svelte';
  import FullscreenControls from './components/FullscreenControls.svelte';
  import SettingsModal from './components/SettingsModal.svelte';
  import TrainingStats from './components/TrainingStats.svelte';
  import FeedbackPopup from './components/FeedbackPopup.svelte';
  import { drumPatterns } from './data/drumPatterns';
  import { trackList } from './data/trackList';
  import { playback } from './stores/playback.svelte';
  import { training } from './stores/training.svelte';
  import { activeDrums } from './stores/activeDrums.svelte';
  import { midi } from './stores/midi.svelte';
  import { keyboard } from './stores/keyboard.svelte';
  import { playDrum, setKit, getActiveKit, getHihatPedalPressed, setHihatPedalAmount } from './audio/drumSounds';
  import { midiConfigs, getNoteMap } from './config/midiConfigs';
  import { drumLayouts } from './config/drumLayouts';
  import { BPM_MIN, BPM_MAX, BPM_STEP, REPS_MIN, PEDAL_CC, PEDAL_THRESHOLD } from './config/constants';
  import type { DrumPattern, SessionResult, Track } from './types';

  const edgePatternIds = new Set(
    drumPatterns.filter(p => p.id.endsWith('-edge')).map(p => p.id.slice(0, -5))
  );

  function getPattern(id: string, edgeMode = false): DrumPattern {
    if (edgeMode && edgePatternIds.has(id)) {
      const edgeP = drumPatterns.find(p => p.id === id + '-edge');
      if (edgeP) return edgeP;
    }
    return drumPatterns.find(p => p.id === id) || drumPatterns[0];
  }

  let selectedPatternId = $state(drumPatterns[0].id);
  let selectedTrackId = $state<string | null>(null);
  let bpmOverride = $state<number | null>(null);
  let stopAfterReps = $state(REPS_MIN);
  let sessionResult = $state<SessionResult | null>(null);
  let activeKitId = $state(getActiveKit().id);
  let kitBusy = $state(false);
  let showVisualizer = $state(false);
  let metronomeOn = $state(false);
  let drumPlaybackOn = $state(true);
  let midiConfigId = $state(midiConfigs[0].id);
  let drumLayoutId = $state(drumLayouts[0].id);
  let showPatterns = $state(true);
  let showHelp = $state(false);
  let fullscreenMode = $state(false);
  let showSettings = $state(false);
  let hihatPedalPressed = $state(getHihatPedalPressed());
  let countdownOn = $state(false);
  let grooveOn = $state(false);
  let edgeMode = $state(false);
  let sessionSet = $state(false);
  let positiveMode = $state(false);
  let feedbackText = $state('');
  let feedbackColor = $state('#4ade80');
  let feedbackVisible = $state(false);
  let feedbackTimer: ReturnType<typeof setTimeout> | null = null;

  let isTrackMode = $derived(selectedTrackId !== null);
  let selectedTrack: Track | null = $derived(isTrackMode ? trackList.find(t => t.id === selectedTrackId!) || null : null);
  let midiNoteMap = $derived(getNoteMap(midiConfigId));
  let pattern = $derived(getPattern(selectedPatternId, edgeMode));
  let patternDefaultBpm = $derived(pattern.bpm);
  let trackDefaultBpm = $derived(selectedTrack?.bpm ?? patternDefaultBpm);
  let defaultBpm = $derived(isTrackMode ? trackDefaultBpm : patternDefaultBpm);
  let effectiveBpm = $derived(bpmOverride || defaultBpm);
  let trainingPattern = $derived(isTrackMode ? (playback.currentPattern || pattern) : pattern);
  let trainingCurrentStep = $derived(playback.currentStep);
  let trainingIsPlaying = $derived(playback.isPlaying);

  function onPatternDrumPlayed(drumId: string, vel: number) {
    activeDrums.hit(drumId, vel);
    hihatPedalPressed = getHihatPedalPressed();
  }

  function onDrumHit(drumId: string, velocity = 0.8) {
    const resolvedId = drumId === 'hihat'
      ? (hihatPedalPressed ? 'hihat' : 'hihatOpen')
      : drumId;
    const prev = getHihatPedalPressed();
    playDrum(resolvedId, velocity);
    training.handleDrumHit(drumId);
    activeDrums.hit(resolvedId, velocity);
    const next = getHihatPedalPressed();
    if (prev !== next) {
      hihatPedalPressed = next;
    }
  }

  function handleCC(controller: number, value: number) {
    if (controller === PEDAL_CC) {
      const amount = Math.min(1, value / 127);
      setHihatPedalAmount(amount);
      hihatPedalPressed = getHihatPedalPressed();
      console.log('pedal', amount.toFixed(2), amount >= PEDAL_THRESHOLD / 127 ? 'closed' : 'open');
    }
  }

  function handleBpmUp() {
    const next = Math.min(BPM_MAX, effectiveBpm + BPM_STEP);
    bpmOverride = next === defaultBpm ? null : next;
  }

  function handleBpmDown() {
    const next = Math.max(BPM_MIN, effectiveBpm - BPM_STEP);
    bpmOverride = next === defaultBpm ? null : next;
  }

  function dismissResult() {
    sessionResult = null;
    sessionSet = false;
    playback.clearRepsComplete();
    playback.stop();
    training.clearHits();
  }

  function handlePatternSelect(id: string) {
    playback.stop();
    selectedTrackId = null;
    selectedPatternId = id;
    bpmOverride = null;
    sessionResult = null;
    sessionSet = false;
  }

  function handleTrackSelect(id: string) {
    playback.stop();
    selectedTrackId = id;
    bpmOverride = null;
    sessionResult = null;
    sessionSet = false;
  }

  function handleBpmChange(value: number) {
    bpmOverride = value === defaultBpm ? null : value;
  }

  function handleToggleVisualizer() {
    showVisualizer = !showVisualizer;
  }

  function handleToggleMetronome() {
    metronomeOn = !metronomeOn;
  }

  function handleToggleDrumPlayback() {
    drumPlaybackOn = !drumPlaybackOn;
  }

  function handleMidiConfigChange(id: string) {
    midiConfigId = id;
  }

  function handleLayoutChange(id: string) {
    drumLayoutId = id;
  }

  function handleHihatPedalToggle() {
    const next = !getHihatPedalPressed();
    setHihatPedalAmount(next ? 1 : 0);
    hihatPedalPressed = next;
  }

  async function handleKitChange(kitId: string) {
    if (kitId === activeKitId) return;
    kitBusy = true;
    try {
      await setKit(kitId);
      activeKitId = kitId;
    } finally {
      kitBusy = false;
    }
  }

  function handleToggleFullscreen() {
    fullscreenMode = !fullscreenMode;
  }

  function handleOpenSettings() {
    showSettings = true;
  }

  function handleCloseSettings() {
    showSettings = false;
  }

  function handleTrainingToggle() {
    sessionResult = null;
    training.setTrainingMode(!training.trainingMode);
  }

  function handleCountdownToggle() {
    countdownOn = !countdownOn;
  }

  function handleGrooveToggle() {
    grooveOn = !grooveOn;
  }

  function handleEdgeModeToggle() {
    edgeMode = !edgeMode;
  }

  function handlePositiveModeToggle() {
    positiveMode = !positiveMode;
  }

  function getTextsForRatio(accuracy: string, ratio: number, savedAvg: number): string[] {
    // Accuracy first
    if (accuracy === 'perfect') return ['Perfect!', 'Flawless!', 'Nailed It!', 'Master!'];
    if (accuracy === 'good') return ['Good!', 'Funky!', 'Beat It!', 'Nice!'];
    // Then improvement (if saved average exists)
    if (savedAvg > 0) {
      const improvement = ratio - savedAvg;
      if (improvement > 0.15) return ['Outstanding!', 'You Crushed It!', 'Personal Best!', 'Amazing!'];
      if (improvement > 0.05) return ['Improved!', 'Better Than Before!', 'Level Up!', 'Progress!'];
    }
    return ['Very Good!', 'You Got It!', 'Great!'];
  }

  function getColorForRatio(accuracy: string, ratio: number, savedAvg: number): string {
    // Accuracy first
    if (accuracy === 'perfect') return '#ef4444'; // red
    if (accuracy === 'good') return '#22c55e'; // green
    // Then improvement
    if (savedAvg > 0) {
      const improvement = ratio - savedAvg;
      if (improvement > 0.15) return '#ef4444'; // red
      if (improvement > 0.05) return '#eab308'; // yellow
    }
    return '#60a5fa'; // blue
  }

  function keyboardTogglePlay() {
    playback.togglePlay();
  }

  function keyboardStop() {
    playback.stop();
  }

  // Sync pattern/track to playback store
  $effect(() => {
    if (isTrackMode) {
      playback.setTrack(selectedTrack);
      training.setTrackId(selectedTrack?.id ?? null);
    } else {
      playback.setTrack(null);
      playback.setPattern(pattern);
    }
  });

  // Sync BPM to playback store
  $effect(() => {
    playback.setBpm(bpmOverride);
  });

  // Sync stopAfterReps to playback store
  $effect(() => {
    playback.setStopAfter(stopAfterReps);
  });

  // Sync onDrumPlayed to playback store
  $effect(() => {
    playback.setOnDrumPlayed(onPatternDrumPlayed);
  });

  // Sync metronomeOn to playback store
  $effect(() => {
    playback.setMetronome(metronomeOn);
  });

  // Sync drumPlaybackOn to playback store
  $effect(() => {
    playback.setDrumPlayback(drumPlaybackOn);
  });

  // Sync countdownOn to playback store
  $effect(() => {
    playback.setCountdown(countdownOn);
  });

  // Sync grooveOn to playback store
  $effect(() => {
    playback.setGroove(grooveOn);
  });

  // Sync pattern to training store
  $effect(() => {
    training.setPattern(trainingPattern);
  });

  // Sync currentStep to training store
  $effect(() => {
    training.setCurrentStep(trainingCurrentStep);
  });

  // Sync isPlaying to training store
  $effect(() => {
    training.setPlaying(trainingIsPlaying);
  });

  // Positive reinforcement feedback
  $effect(() => {
    const accuracy = training.lastHitAccuracy;
    if (positiveMode && accuracy && accuracy !== 'miss') {
      if (accuracy === 'off') {
        feedbackText = ['Almost!', 'Near!', 'Close!'][Math.floor(Math.random() * 3)];
        feedbackColor = '#06b6d4'; // cyan
      } else {
        const ratio = training.hitRatio;
        const savedAvg = training.savedHitRate;
        const texts = getTextsForRatio(accuracy, ratio, savedAvg);
        feedbackText = texts[Math.floor(Math.random() * texts.length)];
        feedbackColor = getColorForRatio(accuracy, ratio, savedAvg);
      }
      feedbackVisible = true;
      if (feedbackTimer) clearTimeout(feedbackTimer);
      feedbackTimer = setTimeout(() => { feedbackVisible = false; }, 800);
    }
  });

  // Session result: pattern mode
  $effect(() => {
    if (playback.repsComplete && training.trainingMode && !isTrackMode && !sessionSet) {
      sessionSet = true;
      sessionResult = {
        stats: training.accuracyStats || { perfect: 0, good: 0, off: 0, miss: 0, total: 0, score: 0 },
        missedHits: training.missedHits,
      };
    }
  });

  // Session result: track mode
  $effect(() => {
    if (playback.isFinished && training.trainingMode && isTrackMode && !sessionSet) {
      sessionSet = true;
      sessionResult = {
        stats: training.accuracyStats || { perfect: 0, good: 0, off: 0, miss: 0, total: 0, score: 0 },
        missedHits: training.missedHits,
      };
    }
  });

  // Set initial kit
  $effect(() => {
    setKit(getActiveKit().id);
  });

  // Setup MIDI
  $effect(() => {
    midi.setOnNoteOn(onDrumHit);
    midi.setNoteMap(midiNoteMap);
    midi.setOnCC(handleCC);
    midi.init();
    return () => { midi.destroy(); };
  });

  // Setup keyboard
  $effect(() => {
    keyboard.setOnNoteOn(onDrumHit);
    keyboard.setActions({
      onTogglePlay: keyboardTogglePlay,
      onStop: keyboardStop,
      onToggleMetronome: handleToggleMetronome,
      onToggleDrumPlayback: handleToggleDrumPlayback,
      onTrainingToggle: handleTrainingToggle,
      onGrooveToggle: handleGrooveToggle,
      onEdgeModeToggle: handleEdgeModeToggle,
      onBpmUp: handleBpmUp,
      onBpmDown: handleBpmDown,
    });
    keyboard.setDisabled(showSettings);
    keyboard.init();
    return () => { keyboard.destroy(); };
  });
</script>

<div class="app">
  <header class="app-header">
    <button
      class="header-btn sidebar-toggle"
      onclick={() => { showPatterns = !showPatterns; }}
      title={showPatterns ? 'Hide patterns' : 'Show patterns'}
    >
      {showPatterns ? '◀' : '▶'}
    </button>
    <h1 class="app-title">Funky Drummer</h1>
    <span class="app-subtitle">Drum Machine & Trainer</span>
    <div class="header-spacer"></div>
    <button
      class="header-btn help-btn"
      onclick={() => { showHelp = true; }}
      title="Help"
    >
      ?
    </button>
    <button
      class="header-btn settings-btn"
      onclick={handleOpenSettings}
      title="Settings"
    >
      ⚙
    </button>
    <button
      class="header-btn fullscreen-btn"
      onclick={handleToggleFullscreen}
      title="Fullscreen"
    >
      ⛶
    </button>
  </header>

  <div class="app-layout">
    {#if showPatterns}
      <aside class="app-sidebar">
        <PatternTrackTabs
          selectedPatternId={selectedPatternId}
          onSelectPattern={handlePatternSelect}
          selectedTrackId={selectedTrackId}
          currentTrackName={playback.currentPattern?.name}
          onSelectTrack={handleTrackSelect}
          isPlayingTrack={playback.isPlaying}
          trackPart={playback.currentPartIndex}
          trackTotalParts={selectedTrack?.parts.length ?? 0}
        />
      </aside>
    {/if}

    <main class="app-main{showPatterns ? '' : ' app-main-full'}">
      <Controls
        isPlaying={playback.isPlaying}
        onTogglePlay={() => playback.togglePlay()}
        onStop={() => playback.stop()}
        bpm={effectiveBpm}
        trainingMode={training.trainingMode}
        onTrainingToggle={handleTrainingToggle}
        accuracyStats={training.accuracyStats ?? undefined}
        missedHits={training.missedHits}
        bpmOverride={bpmOverride}
        onBpmChange={handleBpmChange}
        stopAfterReps={stopAfterReps}
        onStopAfterRepsChange={(v: number) => { stopAfterReps = v; }}
        currentLoop={playback.currentLoop}
        sessionResult={sessionResult}
        onDismissResult={dismissResult}
        showVisualizer={showVisualizer}
        onToggleVisualizer={handleToggleVisualizer}
        metronomeOn={metronomeOn}
        onToggleMetronome={handleToggleMetronome}
        drumPlaybackOn={drumPlaybackOn}
        onToggleDrumPlayback={handleToggleDrumPlayback}
        countdownOn={countdownOn}
        onCountdownToggle={handleCountdownToggle}
        grooveOn={grooveOn}
        onGrooveToggle={handleGrooveToggle}
        edgeMode={edgeMode}
        onEdgeModeToggle={handleEdgeModeToggle}
        trackMode={isTrackMode}
        trackName={selectedTrack?.name ?? ''}
        trackPart={playback.currentPartIndex}
        trackTotalParts={selectedTrack?.parts.length ?? 0}
        positiveMode={positiveMode}
        onPositiveModeToggle={handlePositiveModeToggle}
      />

      <Timeline
        pattern={isTrackMode ? playback.currentPattern : pattern}
        currentStep={playback.currentStep}
        isPlaying={playback.isPlaying}
        userHits={training.userHits}
        trainingMode={training.trainingMode}
        compact={false}
        grooveOn={grooveOn}
        positiveMode={positiveMode}
      />

      {#if showVisualizer}
        <DrumVisualizer activeDrums={activeDrums.activeDrums} onDrumClick={onDrumHit} layoutId={drumLayoutId} hihatPedalPressed={hihatPedalPressed} onHihatPedalDown={handleHihatPedalToggle} />
      {/if}
      {#if training.trainingMode && !positiveMode}
        <div class="fs-stats-stack">
          {#if stopAfterReps > 0}
            <div class="fs-reps-progress-bar">
              <div
                class="fs-reps-progress-fill"
                style="width: {Math.min((playback.currentLoop / stopAfterReps) * 100, 100)}%"
              ></div>
            </div>
          {/if}
          <TrainingStats accuracyStats={training.accuracyStats} missedHits={training.missedHits} />
        </div>
      {/if}
    </main>
  </div>

  {#if fullscreenMode}
    <div class="fullscreen-overlay">
      <header class="app-header fullscreen-header">
        <h1 class="app-title">
          <span class="app-title-text">Funky Drummer</span>
          <span class="app-title-icon">🥁</span>
        </h1>
        <span class="app-subtitle">Drum Machine & Trainer</span>
        <FullscreenControls
          isPlaying={playback.isPlaying}
          onTogglePlay={() => playback.togglePlay()}
          onStop={() => playback.stop()}
          bpm={effectiveBpm}
          onBpmChange={handleBpmChange}
          drumPlaybackOn={drumPlaybackOn}
          onToggleDrumPlayback={handleToggleDrumPlayback}
          trainingMode={training.trainingMode}
          onTrainingToggle={handleTrainingToggle}
          stopAfterReps={stopAfterReps}
          onStopAfterRepsChange={(v: number) => { stopAfterReps = v; }}
          currentLoop={playback.currentLoop}
          grooveOn={grooveOn}
          onGrooveToggle={handleGrooveToggle}
          countdownOn={countdownOn}
          onCountdownToggle={handleCountdownToggle}
        />
        <div class="header-spacer"></div>
        <button
          class="header-btn fullscreen-btn"
          onclick={handleToggleFullscreen}
          title="Exit fullscreen"
        >⛶</button>
      </header>
      <div class="fullscreen-content">
        {#if training.trainingMode && !positiveMode}
          <div class="fs-stats-stack">
            {#if stopAfterReps > 0}
              <div class="fs-reps-progress-bar">
                <div
                  class="fs-reps-progress-fill"
                  style="width: {Math.min((playback.currentLoop / stopAfterReps) * 100, 100)}%"
                ></div>
              </div>
            {/if}
            <TrainingStats accuracyStats={training.accuracyStats} missedHits={training.missedHits} />
          </div>
        {/if}
        <Timeline
          pattern={isTrackMode ? playback.currentPattern : pattern}
          currentStep={playback.currentStep}
          isPlaying={playback.isPlaying}
          userHits={training.userHits}
          trainingMode={training.trainingMode}
          compact={true}
          grooveOn={grooveOn}
          positiveMode={positiveMode}
        />
        <div class="fs-viz-area">
          <DrumVisualizer activeDrums={activeDrums.activeDrums} onDrumClick={onDrumHit} layoutId={drumLayoutId} hihatPedalPressed={hihatPedalPressed} onHihatPedalDown={handleHihatPedalToggle} />
        </div>
      </div>
    </div>
  {/if}

  {#if playback.isCountdown}
    <div class="countdown-overlay">
      <span class="countdown-number">
        {Math.ceil(playback.countdownCount / 4) - 1}
      </span>
    </div>
  {/if}

  <FeedbackPopup text={feedbackText} color={feedbackColor} visible={feedbackVisible} />

  {#if showSettings}
    <SettingsModal
      onClose={handleCloseSettings}
      activeKitId={activeKitId}
      onKitChange={handleKitChange}
      kitBusy={kitBusy}
      drumLayoutId={drumLayoutId}
      onLayoutChange={handleLayoutChange}
      showVisualizer={showVisualizer}
      midiInputs={midi.inputs}
      activeInput={midi.activeInput}
      onInputChange={midi.selectInput}
      midiConfigId={midiConfigId}
      onMidiConfigChange={handleMidiConfigChange}
    />
  {/if}
  {#if showHelp}
    <HelpModal onClose={() => { showHelp = false; }} />
  {/if}
</div>

// src/App.jsx
import { useState, useCallback, useEffect, useRef } from 'react';
import Timeline from './components/Timeline';
import PatternTrackTabs from './components/PatternTrackTabs';
import Controls from './components/Controls';
import DrumVisualizer from './components/DrumVisualizer';
import HelpModal from './components/HelpModal';
import FullscreenControls from './components/FullscreenControls';
import SettingsModal from './components/SettingsModal';
import { drumPatterns } from './data/drumPatterns';
import { trackList } from './data/trackList';
import { useMIDI } from './hooks/useMIDI';
import { useKeyboard } from './hooks/useKeyboard';
import { usePlayback } from './hooks/usePlayback';
import { useTrackPlayback } from './hooks/useTrackPlayback';
import { useTraining } from './hooks/useTraining';
import { useActiveDrums } from './hooks/useActiveDrums';
import { playDrum, setKit, getActiveKit, isKitLoading, getHihatPedalPressed, setHihatPedalPressed } from './audio/drumSounds';
import { drumKits } from './config/drumKits';
import { midiConfigs, getNoteMap } from './config/midiConfigs';
import { drumLayouts } from './config/drumLayouts';
import { BPM_MIN, BPM_MAX, BPM_STEP, REPS_MIN, PEDAL_CC, PEDAL_THRESHOLD, GOOD_SCORE_THRESHOLD, OK_SCORE_THRESHOLD } from './config/constants';
import './App.css';

const edgePatternIds = new Set(
  drumPatterns.filter(p => p.id.endsWith('-edge')).map(p => p.id.slice(0, -5))
);

function getPattern(id, edgeMode = false) {
  if (edgeMode && edgePatternIds.has(id)) {
    const edgeP = drumPatterns.find(p => p.id === id + '-edge');
    if (edgeP) return edgeP;
  }
  return drumPatterns.find(p => p.id === id) || drumPatterns[0];
}

export default function App() {
  const [selectedPatternId, setSelectedPatternId] = useState(drumPatterns[0].id);
  const [selectedTrackId, setSelectedTrackId] = useState(null);
  const isTrackMode = selectedTrackId !== null;
  const selectedTrack = isTrackMode ? trackList.find(t => t.id === selectedTrackId) : null;
  const [bpmOverride, setBpmOverride] = useState(null);
  const [stopAfterReps, setStopAfterReps] = useState(REPS_MIN);
  const [sessionResult, setSessionResult] = useState(null);
  const [activeKitId, setActiveKitId] = useState(getActiveKit().id);
  const [kitBusy, setKitBusy] = useState(false);
  const [showVisualizer, setShowVisualizer] = useState(false);
  const [metronomeOn, setMetronomeOn] = useState(false);
  const [drumPlaybackOn, setDrumPlaybackOn] = useState(true);
  const [midiConfigId, setMidiConfigId] = useState(midiConfigs[0].id);
  const [drumLayoutId, setDrumLayoutId] = useState(drumLayouts[0].id);
  const [showPatterns, setShowPatterns] = useState(true);
  const [showHelp, setShowHelp] = useState(false);
  const [fullscreenMode, setFullscreenMode] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [hihatPedalPressed, setHihatPedalPressedState] = useState(getHihatPedalPressed());
  const [countdownOn, setCountdownOn] = useState(false);
  const [grooveOn, setGrooveOn] = useState(false);
  const [edgeMode, setEdgeMode] = useState(false);
  const sessionSetRef = useRef(false);
  const midiNoteMap = getNoteMap(midiConfigId);

  const { activeDrums, hit: hitVisualizer } = useActiveDrums();

  const pattern = getPattern(selectedPatternId, edgeMode);

  const onPatternDrumPlayed = useCallback((drumId, vel) => {
    hitVisualizer(drumId, vel);
    setHihatPedalPressedState(getHihatPedalPressed());
  }, [hitVisualizer]);

  const playback = usePlayback(pattern, bpmOverride, stopAfterReps, onPatternDrumPlayed, metronomeOn, drumPlaybackOn, countdownOn, grooveOn);
  const trackPlayback = useTrackPlayback(selectedTrack, onPatternDrumPlayed, metronomeOn, drumPlaybackOn, bpmOverride);

  const patternDefaultBpm = pattern.bpm;
  const trackDefaultBpm = selectedTrack?.bpm ?? patternDefaultBpm;
  const defaultBpm = isTrackMode ? trackDefaultBpm : patternDefaultBpm;
  const effectiveBpm = bpmOverride || defaultBpm;

  const trainingPattern = isTrackMode ? trackPlayback.currentPattern : pattern;
  const trainingCurrentStep = isTrackMode ? trackPlayback.currentStep : playback.currentStep;
  const trainingIsPlaying = isTrackMode ? trackPlayback.isPlaying : playback.isPlaying;
  const {
    trainingMode,
    setTrainingMode,
    userHits,
    handleDrumHit,
    clearHits,
    accuracyStats,
    missedHits,
  } = useTraining(trainingPattern, trainingCurrentStep, trainingIsPlaying);

  const onDrumHit = useCallback((drumId, velocity) => {
    const resolvedId = drumId === 'hihat'
      ? (hihatPedalPressed ? 'hihat' : 'hihatOpen')
      : drumId;
    const prev = getHihatPedalPressed();
    playDrum(resolvedId, velocity);
    handleDrumHit(drumId);
    hitVisualizer(resolvedId, velocity);
    const next = getHihatPedalPressed();
    if (prev !== next) {
      setHihatPedalPressedState(next);
    }
  }, [handleDrumHit, hitVisualizer, hihatPedalPressed]);

  const handleCC = useCallback((controller, value) => {
    if (controller === PEDAL_CC) {
      const pressed = value >= PEDAL_THRESHOLD;
      setHihatPedalPressedState(pressed);
      setHihatPedalPressed(pressed);
      console.log('pedal', pressed ? 'closed' : 'open');
    }
  }, []);

  const { inputs, activeInput, setActiveInput } = useMIDI(onDrumHit, midiNoteMap, handleCC);
  const handleBpmUp = useCallback(() => {
    const next = Math.min(BPM_MAX, effectiveBpm + BPM_STEP);
    setBpmOverride(next === defaultBpm ? null : next);
  }, [effectiveBpm, defaultBpm]);

  const handleBpmDown = useCallback(() => {
    const next = Math.max(BPM_MIN, effectiveBpm - BPM_STEP);
    setBpmOverride(next === defaultBpm ? null : next);
  }, [effectiveBpm, defaultBpm]);

  useEffect(() => {
    if (playback.repsComplete && trainingMode && !isTrackMode && !sessionSetRef.current) {
      sessionSetRef.current = true;
      setSessionResult({
        stats: accuracyStats || { perfect: 0, good: 0, off: 0, miss: 0, total: 0, score: 0 },
        missedHits,
      });
    }
  }, [playback.repsComplete, trainingMode, accuracyStats, isTrackMode]);

  useEffect(() => {
    if (trackPlayback.isFinished && trainingMode && isTrackMode && !sessionSetRef.current) {
      sessionSetRef.current = true;
      setSessionResult({
        stats: accuracyStats || { perfect: 0, good: 0, off: 0, miss: 0, total: 0, score: 0 },
        missedHits,
      });
    }
  }, [trackPlayback.isFinished, trainingMode, accuracyStats, isTrackMode]);

  const dismissResult = useCallback(() => {
    setSessionResult(null);
    sessionSetRef.current = false;
    playback.clearRepsComplete();
    trackPlayback.stop();
    clearHits();
  }, [clearHits, playback.clearRepsComplete, trackPlayback.stop]);

  const handlePatternSelect = useCallback((id) => {
    playback.stop();
    trackPlayback.stop();
    setSelectedTrackId(null);
    setSelectedPatternId(id);
    setBpmOverride(null);
    setSessionResult(null);
    sessionSetRef.current = false;
  }, [playback.stop, trackPlayback.stop]);

  const handleTrackSelect = useCallback((id) => {
    playback.stop();
    trackPlayback.stop();
    setSelectedTrackId(id);
    setBpmOverride(null);
    setSessionResult(null);
    sessionSetRef.current = false;
  }, [playback.stop, trackPlayback.stop]);

  const handleBpmChange = useCallback((value) => {
    setBpmOverride(value === defaultBpm ? null : value);
  }, [defaultBpm]);

  const handleToggleVisualizer = useCallback(() => {
    setShowVisualizer(v => !v);
  }, []);

  const handleToggleMetronome = useCallback(() => {
    setMetronomeOn(v => !v);
  }, []);

  const handleToggleDrumPlayback = useCallback(() => {
    setDrumPlaybackOn(v => !v);
  }, []);

  const handleMidiConfigChange = useCallback((id) => {
    setMidiConfigId(id);
  }, []);

  const handleLayoutChange = useCallback((id) => {
    setDrumLayoutId(id);
  }, []);

  const handleHihatPedalToggle = useCallback(() => {
    const next = !getHihatPedalPressed();
    setHihatPedalPressedState(next);
    setHihatPedalPressed(next);
  }, []);

  const handleHihatPedalUp = useCallback(() => {
    // release only — no state change
  }, []);

  const handleKitChange = useCallback(async (kitId) => {
    if (kitId === activeKitId) return;
    setKitBusy(true);
    await setKit(kitId);
    setActiveKitId(kitId);
    setKitBusy(false);
  }, [activeKitId]);

  useEffect(() => {
    setKit(getActiveKit().id);
  }, []);

  const handleToggleFullscreen = useCallback(() => {
    setFullscreenMode(v => !v);
  }, []);

  const handleOpenSettings = useCallback(() => {
    setShowSettings(true);
  }, []);

  const handleCloseSettings = useCallback(() => {
    setShowSettings(false);
  }, []);

  const handleTrainingToggle = useCallback(() => {
    setSessionResult(null);
    setTrainingMode(!trainingMode);
  }, [trainingMode]);

  const handleCountdownToggle = useCallback(() => {
    setCountdownOn(v => !v);
  }, []);

  const handleGrooveToggle = useCallback(() => {
    setGrooveOn(v => !v);
  }, []);

  const handleEdgeModeToggle = useCallback(() => {
    setEdgeMode(v => !v);
  }, []);

  const keyboardTogglePlay = useCallback(() => {
    if (isTrackMode) trackPlayback.togglePlay();
    else playback.togglePlay();
  }, [isTrackMode, trackPlayback.togglePlay, playback.togglePlay]);

  const keyboardStop = useCallback(() => {
    if (isTrackMode) trackPlayback.stop();
    else playback.stop();
  }, [isTrackMode, trackPlayback.stop, playback.stop]);

  useKeyboard(onDrumHit, {
    onTogglePlay: keyboardTogglePlay,
    onStop: keyboardStop,
    onToggleMetronome: handleToggleMetronome,
    onToggleDrumPlayback: handleToggleDrumPlayback,
    onTrainingToggle: handleTrainingToggle,
    onGrooveToggle: handleGrooveToggle,
    onEdgeModeToggle: handleEdgeModeToggle,
    onBpmUp: handleBpmUp,
    onBpmDown: handleBpmDown,
  }, showSettings);

  return (
    <div className="app">
      <header className="app-header">
        <button
          className="header-btn sidebar-toggle"
          onClick={() => setShowPatterns(v => !v)}
          title={showPatterns ? 'Hide patterns' : 'Show patterns'}
        >
          {showPatterns ? '◀' : '▶'}
        </button>
        <h1 className="app-title">Funky Drummer</h1>
        <span className="app-subtitle">Drum Machine & Trainer</span>
        <div className="header-spacer" />
        <button
          className="header-btn help-btn"
          onClick={() => setShowHelp(true)}
          title="Help"
        >
          ?
        </button>
        <button
          className="header-btn settings-btn"
          onClick={handleOpenSettings}
          title="Settings"
        >
          ⚙
        </button>
        <button
          className="header-btn fullscreen-btn"
          onClick={handleToggleFullscreen}
          title="Fullscreen"
        >
          ⛶
        </button>
      </header>

      <div className="app-layout">
        {showPatterns && (
          <aside className="app-sidebar">
            <PatternTrackTabs
              selectedPatternId={selectedPatternId}
              onSelectPattern={handlePatternSelect}
              selectedTrackId={selectedTrackId}
              currentTrackName={trackPlayback.currentPattern?.name}
              onSelectTrack={handleTrackSelect}
              isPlayingTrack={trackPlayback.isPlaying}
              trackPart={trackPlayback.currentPartIndex}
              trackTotalParts={selectedTrack?.parts.length ?? 0}
            />
          </aside>
        )}

        <main className={`app-main${showPatterns ? '' : ' app-main-full'}`}>
          <Controls
            isPlaying={isTrackMode ? trackPlayback.isPlaying : playback.isPlaying}
            onTogglePlay={isTrackMode ? trackPlayback.togglePlay : playback.togglePlay}
            onStop={isTrackMode ? trackPlayback.stop : playback.stop}
            bpm={effectiveBpm}
            trainingMode={trainingMode}
            onTrainingToggle={handleTrainingToggle}
            accuracyStats={accuracyStats}
            missedHits={missedHits}
            bpmOverride={bpmOverride}
            onBpmChange={handleBpmChange}
            stopAfterReps={stopAfterReps}
            onStopAfterRepsChange={setStopAfterReps}
            currentLoop={playback.currentLoop}
            sessionResult={sessionResult}
            onDismissResult={dismissResult}
            showVisualizer={showVisualizer}
            onToggleVisualizer={handleToggleVisualizer}
            metronomeOn={metronomeOn}
            onToggleMetronome={handleToggleMetronome}
            drumPlaybackOn={drumPlaybackOn}
            onToggleDrumPlayback={handleToggleDrumPlayback}
            countdownOn={countdownOn}
            onCountdownToggle={handleCountdownToggle}
            grooveOn={grooveOn}
            onGrooveToggle={handleGrooveToggle}
            edgeMode={edgeMode}
            onEdgeModeToggle={handleEdgeModeToggle}
            trackMode={isTrackMode}
            trackName={selectedTrack?.name ?? ''}
            trackPart={trackPlayback.currentPartIndex}
            trackTotalParts={selectedTrack?.parts.length ?? 0}
          />

          <Timeline
            pattern={isTrackMode ? trackPlayback.currentPattern : pattern}
            currentStep={isTrackMode ? trackPlayback.currentStep : playback.currentStep}
            isPlaying={isTrackMode ? trackPlayback.isPlaying : playback.isPlaying}
            userHits={userHits}
            trainingMode={trainingMode}
            compact={false}
            grooveOn={grooveOn}
          />

          {showVisualizer && (
            <DrumVisualizer activeDrums={activeDrums} onDrumClick={onDrumHit} layoutId={drumLayoutId} hihatPedalPressed={hihatPedalPressed} onHihatPedalDown={handleHihatPedalToggle} onHihatPedalUp={handleHihatPedalUp} />
          )}
          {trainingMode && (
            <div className="fs-stats-stack">
              {stopAfterReps > 0 && (
                <div className="fs-reps-progress-bar">
                  <div
                    className="fs-reps-progress-fill"
                    style={{ width: `${Math.min((playback.currentLoop / stopAfterReps) * 100, 100)}%` }}
                  />
                </div>
              )}
              {accuracyStats ? (
                <>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Acc</span>
                    <span className={`fs-stat-value ${accuracyStats.score >= GOOD_SCORE_THRESHOLD ? 'good' : accuracyStats.score >= OK_SCORE_THRESHOLD ? 'ok' : 'bad'}`}>
                      {accuracyStats.score}%
                    </span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Perfect</span>
                    <span className="fs-stat-value perfect">{accuracyStats.perfect}</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Good</span>
                    <span className="fs-stat-value good">{accuracyStats.good}</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Off</span>
                    <span className="fs-stat-value off">{accuracyStats.off}</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Extra</span>
                    <span className="fs-stat-value miss">{accuracyStats.miss}</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Missed</span>
                    <span className="fs-stat-value miss">{missedHits}</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Total</span>
                    <span className="fs-stat-value total">{accuracyStats.total}</span>
                  </div>
                </>
              ) : (
                <>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Acc</span>
                    <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Perfect</span>
                    <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Good</span>
                    <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Off</span>
                    <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Extra</span>
                    <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Missed</span>
                    <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                  </div>
                  <div className="fs-stat">
                    <span className="fs-stat-label">Total</span>
                    <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                  </div>
                </>
              )}
            </div>
          )}
        </main>
      </div>

      {fullscreenMode && (
        <div className="fullscreen-overlay">
          <header className="app-header fullscreen-header">
            <h1 className="app-title">
              <span className="app-title-text">Funky Drummer</span>
              <span className="app-title-icon">🥁</span>
            </h1>
            <span className="app-subtitle">Drum Machine & Trainer</span>
            <FullscreenControls
              isPlaying={isTrackMode ? trackPlayback.isPlaying : playback.isPlaying}
              onTogglePlay={isTrackMode ? trackPlayback.togglePlay : playback.togglePlay}
              onStop={isTrackMode ? trackPlayback.stop : playback.stop}
            bpm={effectiveBpm}
              onBpmChange={handleBpmChange}
              drumPlaybackOn={drumPlaybackOn}
              onToggleDrumPlayback={handleToggleDrumPlayback}
              trainingMode={trainingMode}
              onTrainingToggle={handleTrainingToggle}
              stopAfterReps={stopAfterReps}
              onStopAfterRepsChange={setStopAfterReps}
              currentLoop={playback.currentLoop}
              grooveOn={grooveOn}
              onGrooveToggle={handleGrooveToggle}
              countdownOn={countdownOn}
              onCountdownToggle={handleCountdownToggle}
            />
            <div className="header-spacer" />
            <button
              className="header-btn fullscreen-btn"
              onClick={handleToggleFullscreen}
              title="Exit fullscreen"
            >⛶</button>
          </header>
          <div className="fullscreen-content">
            {trainingMode && (
              <div className="fs-stats-stack">
                {stopAfterReps > 0 && (
                  <div className="fs-reps-progress-bar">
                    <div
                      className="fs-reps-progress-fill"
                      style={{ width: `${Math.min((playback.currentLoop / stopAfterReps) * 100, 100)}%` }}
                    />
                  </div>
                )}
                {accuracyStats ? (
                  <>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Acc</span>
                      <span className={`fs-stat-value ${accuracyStats.score >= GOOD_SCORE_THRESHOLD ? 'good' : accuracyStats.score >= OK_SCORE_THRESHOLD ? 'ok' : 'bad'}`}>
                        {accuracyStats.score}%
                      </span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Perfect</span>
                      <span className="fs-stat-value perfect">{accuracyStats.perfect}</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Good</span>
                      <span className="fs-stat-value good">{accuracyStats.good}</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Off</span>
                      <span className="fs-stat-value off">{accuracyStats.off}</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Extra</span>
                      <span className="fs-stat-value miss">{accuracyStats.miss}</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Missed</span>
                      <span className="fs-stat-value miss">{missedHits}</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Total</span>
                      <span className="fs-stat-value total">{accuracyStats.total}</span>
                    </div>
                  </>
                ) : (
                  <>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Acc</span>
                      <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Perfect</span>
                      <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Good</span>
                      <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Off</span>
                      <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Extra</span>
                      <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Missed</span>
                      <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                    </div>
                    <div className="fs-stat">
                      <span className="fs-stat-label">Total</span>
                      <span className="fs-stat-value" style={{ color: '#555' }}>-</span>
                    </div>
                  </>
                )}
              </div>
            )}
            <Timeline
              pattern={isTrackMode ? trackPlayback.currentPattern : pattern}
              currentStep={isTrackMode ? trackPlayback.currentStep : playback.currentStep}
              isPlaying={isTrackMode ? trackPlayback.isPlaying : playback.isPlaying}
              userHits={userHits}
              trainingMode={trainingMode}
              compact={true}
              grooveOn={grooveOn}
            />
            <div className="fs-viz-area">
              <DrumVisualizer activeDrums={activeDrums} onDrumClick={onDrumHit} layoutId={drumLayoutId} hihatPedalPressed={hihatPedalPressed} onHihatPedalDown={handleHihatPedalToggle} onHihatPedalUp={handleHihatPedalUp} />
            </div>
          </div>
        </div>
      )}

      {playback.isCountdown && (
        <div className="countdown-overlay">
          <span className="countdown-number" key={Math.ceil(playback.countdownCount / 4)}>
            {Math.ceil(playback.countdownCount / 4) - 1}
          </span>
        </div>
      )}

      {showSettings && (
        <SettingsModal
          onClose={handleCloseSettings}
          activeKitId={activeKitId}
          onKitChange={handleKitChange}
          kitBusy={kitBusy}
          drumLayoutId={drumLayoutId}
          onLayoutChange={handleLayoutChange}
          showVisualizer={showVisualizer}
          midiInputs={inputs}
          activeInput={activeInput}
          onInputChange={setActiveInput}
          midiConfigId={midiConfigId}
          onMidiConfigChange={handleMidiConfigChange}
        />
      )}
      {showHelp && <HelpModal onClose={() => setShowHelp(false)} />}
    </div>
  );
}
